import Head from 'next/head';
import type { NextPage } from 'next';
import Header from '@components/Header';
import { main } from '@shared/home';
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>All About Next JS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main css={main}>
        <Header />
      </main>
    </>
  );
};

export default Home;
